(define (domain robot_abstract)
  (:requirements :typing)
  (:types state)
  (:predicates
    (At ?s - state)
    (Pre-TurnAway ?s - state)
    (Eff-TurnAway ?s - state)
    (Trans-TurnAway ?from - state ?to - state)
    (Pre-Approach ?s - state)
    (Eff-Approach ?s - state)
    (Trans-Approach ?from - state ?to - state)
    (Pre-TurnRight ?s - state)
    (Eff-TurnRight ?s - state)
    (Trans-TurnRight ?from - state ?to - state)
    (Pre-TurnLeft ?s - state)
    (Eff-TurnLeft ?s - state)
    (Trans-TurnLeft ?from - state ?to - state)
  )

  (:action TurnAway
    :parameters (?from - state ?to - state)
    :precondition (and (At ?from) (Trans-TurnAway ?from ?to) (Pre-TurnAway ?from))
    :effect (and (not (At ?from)) (At ?to) (Eff-TurnAway ?to))
  )
  (:action Approach
    :parameters (?from - state ?to - state)
    :precondition (and (At ?from) (Trans-Approach ?from ?to) (Pre-Approach ?from))
    :effect (and (not (At ?from)) (At ?to) (Eff-Approach ?to))
  )
  (:action TurnRight
    :parameters (?from - state ?to - state)
    :precondition (and (At ?from) (Trans-TurnRight ?from ?to) (Pre-TurnRight ?from))
    :effect (and (not (At ?from)) (At ?to) (Eff-TurnRight ?to))
  )
  (:action TurnLeft
    :parameters (?from - state ?to - state)
    :precondition (and (At ?from) (Trans-TurnLeft ?from ?to) (Pre-TurnLeft ?from))
    :effect (and (not (At ?from)) (At ?to) (Eff-TurnLeft ?to))
  )
)