(define (problem find_end_pad)
  (:domain robot_exploration)
  (:objects
    s0 s1 s2 s3 s4 s5 s6 s7 s8 - state
  )

  (:init
    (At s0)

    (Eff-TurnAway s0)
    (Eff-TurnLeft s0)
    (Eff-TurnRight s0)
    (Pre-Approach s0)
    (Pre-TurnLeft s0)
    (Pre-TurnRight s0)
    (Eff-Approach s2)
    (Eff-TurnRight s2)
    (Pre-TurnAway s2)
    (Pre-TurnLeft s2)
    (Eff-TurnLeft s3)
    (Eff-TurnRight s3)
    (Pre-Approach s3)
    (Pre-TurnAway s3)
    (Pre-TurnLeft s3)
    (Eff-TurnAway s4)
    (Eff-TurnLeft s4)
    (Eff-TurnRight s4)
    (Pre-Approach s4)
    (Pre-TurnAway s4)
    (Eff-Approach s5)
    (Pre-TurnAway s5)
    (Pre-TurnRight s5)
    (Eff-TurnLeft s6)
    (Eff-TurnAway s7)
    (Eff-Approach s8)
    (Pre-TurnLeft s8)

    (Trans-TurnLeft s0 s6)
    (Trans-Approach s4 s8)
    (Trans-Approach s3 s2)
    (Trans-TurnLeft s3 s0)
    (Trans-Approach s4 s2)
    (Trans-TurnLeft s2 s0)
    (Trans-Approach s0 s8)
    (Trans-TurnAway s4 s0)
    (Trans-TurnRight s5 s0)
    (Trans-TurnRight s0 s2)
    (Trans-TurnLeft s2 s3)
    (Trans-TurnRight s0 s3)
    (Trans-Approach s0 s5)
    (Trans-TurnAway s5 s4)
    (Trans-TurnAway s2 s7)
    (Trans-TurnLeft s2 s4)
    (Trans-TurnAway s3 s4)
    (Trans-TurnRight s0 s4)
    (Trans-TurnLeft s8 s4)
  )

  (:goal
    (At s_unknown_goal) ;; Goal was not found during exploration!
  )
)